# Generated by Django 6.0.5 on 2026-05-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_order_address_line_order_city_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
    ]
