# Generated by Django 6.0.5 on 2026-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_menuitem_is_coming_soon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('wallet', 'Wallet')], default='upi', max_length=20),
        ),
    ]
